### ISSUE TITLE
Format error on markup when importing from Lokalise to iOS

### ISSUE THREAD

**Issue by Tibimac** [happn-tech/LocMapper#4]
Key exemple with problem : `login_sos_confirmation_used_email`
String in Lokalise : 

> Click on the validation link sent to \*[%1$s]* to confirm your account.

Output in LocMapper/Xcode (mapping 1-1) : 

> Click on the validation link sent to \*%1$s* to confirm your account.

**Comment by Frizlab** [comment]
This is due to LocMapper universal placeholder feature: https://docs.lokalise.com/en/articles/1400511-lokalise-placeholders. We convert universal placeholders to the printf style placeholder (currently; previously we asked Lokalise to do it for us directly at download time).
